In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten

In [4]:
model=Sequential()

In [5]:
model.add(Convolution2D(48,(3,3),input_shape=(64,64,3),activation="relu"))

In [6]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [7]:
model.add(Flatten())

In [8]:
model.add(Dense(kernel_initializer="random_uniform",activation="relu",units=150))

In [9]:
model.add(Dense(kernel_initializer="random_uniform",activation="softmax",units=5))

In [10]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [11]:
from keras.preprocessing.image import ImageDataGenerator

In [12]:
train_datagen=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
test_datagen= ImageDataGenerator(rescale=1./255)

In [13]:
x_train = train_datagen.flow_from_directory(r'C:\Users\saira\Downloads\ECG_Arrhythmia_Dataset\ECG_Datasets\Training_dataset',target_size = (64, 64),batch_size = 32,class_mode = 'categorical')
x_test = test_datagen.flow_from_directory(r'C:\Users\saira\Downloads\ECG_Arrhythmia_Dataset\ECG_Datasets\Test_dataset',target_size = (64, 64),batch_size = 32,class_mode = 'categorical')

Found 2600 images belonging to 5 classes.
Found 650 images belonging to 5 classes.


In [14]:
x_train.class_indices

{'Fusion_beat': 0,
 'Normal_beat': 1,
 'Supraventricular_ectopic_beat': 2,
 'Unknown_beat': 3,
 'Ventricular_ectopic_beat': 4}

In [15]:
model.fit_generator(x_train, steps_per_epoch=500, epochs=12,validation_data=x_test)


Epoch 1/12
500/500 [==============================] - 97s 194ms/step - loss: 1.2367 - accuracy: 0.4719 - val_loss: 1.5642 - val_accuracy: 0.3138
Epoch 2/12
500/500 [==============================] - 93s 187ms/step - loss: 0.5245 - accuracy: 0.8158 - val_loss: 2.4804 - val_accuracy: 0.4323
Epoch 3/12
500/500 [==============================] - 96s 193ms/step - loss: 0.3882 - accuracy: 0.8670 - val_loss: 2.6552 - val_accuracy: 0.4154
Epoch 4/12
500/500 [==============================] - 93s 187ms/step - loss: 0.3318 - accuracy: 0.8909 - val_loss: 5.9044 - val_accuracy: 0.4062
Epoch 5/12
500/500 [==============================] - 92s 185ms/step - loss: 0.2761 - accuracy: 0.9071 - val_loss: 2.7596 - val_accuracy: 0.4831
Epoch 6/12
500/500 [==============================] - 93s 186ms/step - loss: 0.2392 - accuracy: 0.9194 - val_loss: 2.4620 - val_accuracy: 0.4677
Epoch 7/12
500/500 [==============================] - 93s 185ms/step - loss: 0.2134 - accuracy: 0.9306 - val_loss: 4.9629 - val_a

In [16]:
model.save('ECG.h5')

In [17]:
from tensorflow.keras.models import load_model
import numpy as np

In [18]:
model = load_model('ECG.h5')
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

from skimage.transform import resize

def detect(frame):
    try:
        beat_type=['Fusion beat','Normal beat','Supraventricular ectopic beat','unknown beat','Ventricular ectopic beat']
        img = resize(frame,(64,64))
        img = np.expand_dims(img,axis=0)
        if(np.max(img)>1):
            img = img/255.0
        prediction = model.predict(img)
        print(prediction)
        prediction = model.predict_classes(img)
        print(beat_type[prediction[0]])
    except AttributeError:
        print("shape not found")

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [19]:
import cv2
path=r'C:\Users\saira\Downloads\ECG_Arrhythmia_Dataset\ECG_Datasets\Training_dataset\Normal_beat\fig_1.png'


In [20]:
frame=cv2.imread(r'C:\Users\saira\Downloads\ECG_Arrhythmia_Dataset\ECG_Datasets\Training_dataset\Normal_beat\fig_1.png')
data=detect(frame)

[[2.5920290e-04 9.8288745e-01 1.6719677e-02 1.0394892e-04 2.9789364e-05]]
Normal beat


In [21]:
path=r'C:\Users\saira\Downloads\ECG_Arrhythmia_Dataset\ECG_Datasets\Training_dataset\Fusion_beat\Ffig_1.png'

In [22]:
frame=cv2.imread(path)
data=detect(frame)

[[7.9585475e-01 1.3475311e-03 1.8954007e-01 4.0622701e-05 1.3217189e-02]]
Fusion beat


In [23]:
path=r'C:\Users\saira\OneDrive\Desktop\intership\ECG_Datasets\Training_dataset\Unknown_beat\ffig_31200001.png'
data=detect(cv2.imread(path))

[[9.483532e-04 8.948591e-06 8.470675e-06 9.990281e-01 6.240168e-06]]
unknown beat


In [24]:
path=r'C:\Users\saira\OneDrive\Desktop\intership\ECG_Datasets\Training_dataset\Unknown_beat\ffig_31200011.png'
data=detect(cv2.imread(path))

[[1.5961865e-02 2.8765868e-07 3.3806398e-04 9.8355973e-01 1.4001576e-04]]
unknown beat


In [25]:
path=r'C:\Users\saira\OneDrive\Desktop\intership\ECG_Datasets\Training_dataset\Ventricular_ectopic_beat\Efig_93.png'
data=detect(cv2.imread(path))

[[7.4343063e-02 1.1580101e-06 6.8185655e-05 4.1961681e-02 8.8362592e-01]]
Ventricular ectopic beat


In [26]:
path=r'C:\Users\saira\OneDrive\Desktop\intership\ECG_Datasets\Training_dataset\Ventricular_ectopic_beat\Efig_105.png'
data=detect(cv2.imread(path))

[[1.2474335e-03 8.2573379e-08 9.7128350e-06 1.4671840e-03 9.9727565e-01]]
Ventricular ectopic beat


In [27]:
path=r'C:\Users\saira\OneDrive\Desktop\intership\ECG_Datasets\Training_dataset\Supraventricular_ectopic_beat\Afig_5.png'
data=detect(cv2.imread(path))

[[0.01292053 0.29561824 0.64665234 0.04238842 0.00242052]]
Supraventricular ectopic beat


In [28]:
path=r'C:\Users\saira\OneDrive\Desktop\intership\ECG_Datasets\Training_dataset\Supraventricular_ectopic_beat\Afig_1.png'
data=detect(cv2.imread(path))

[[7.2256086e-04 9.6688461e-01 3.2331437e-02 4.7431797e-05 1.3776440e-05]]
Normal beat


In [29]:
path=r'C:\Users\saira\OneDrive\Desktop\intership\ECG_Datasets\Test_dataset\Fusion_beat\Ffig_652.png'
data=detect(cv2.imread(path))

[[9.9727136e-01 9.6040537e-07 2.3151191e-04 3.3852405e-06 2.4928930e-03]]
Fusion beat
